#!/usr/bin/env bash
# emit-inventory.sh — render ISCP Appendix H from the raw discovery JSON.
# Pure rendering: reads only files under --in, makes no API calls.

set -uo pipefail
IN="discovery-output"; OUT="discovery-output/inventory.md"; REGIONS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --in) IN="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        --regions) REGIONS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

HAVE_JQ=0; command -v jq >/dev/null 2>&1 && HAVE_JQ=1

j() { [ "$HAVE_JQ" -eq 1 ] && [ -f "$1" ] && jq -r "$2" "$1" 2>/dev/null || true; }

section() {  # section TITLE FILE FILTER HEADER
    local title="$1" file="$2" filter="$3" header="$4"
    printf '\n### %s\n\n' "$title" >> "$OUT"
    if [ ! -f "$file" ]; then
        printf '_Not discovered. See `gaps.md`._\n' >> "$OUT"; return
    fi
    local rows; rows="$(j "$file" "$filter")"
    if [ -z "$rows" ]; then
        printf '_None found in this compartment and region._\n' >> "$OUT"; return
    fi
    printf '%s\n' "$header" >> "$OUT"
    printf '%s\n' "$rows" >> "$OUT"
}

{
    printf '# Appendix H — Hardware, software and resource inventory\n\n'
    printf '> Generated by `itscm-onboarding/scripts/discover/oci-discover.sh` on %s.\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '> **Read-only walk.** No resource was created, modified or deleted.\n\n'
    printf '> ### This inventory is known-incomplete by construction\n> \n'
    printf '> It lists what the walk could read. Anything the CLI could not reach is in\n'
    printf '> `gaps.md` with the reason. **Absence from this file is absence of evidence,\n'
    printf '> not evidence of absence** — do not read a missing section as a missing resource.\n> \n'
    printf '> It also cannot tell you what any of this is *for*. Business meaning comes from\n'
    printf '> the application owner, not from a resource listing.\n\n'
    printf 'Regions walked: `%s`\n' "${REGIONS:-unknown}"
} > "$OUT"

IFS=',' read -r -a RL <<< "${REGIONS:-}"
for R in "${RL[@]}"; do
    printf '\n---\n\n## %s\n' "$R" >> "$OUT"

    section "Availability domains" "$IN/raw/$R.availability-domains.json" \
        '.data[] | "| \(.name) |"' \
        '| Availability domain |
|---|'

    section "Exadata infrastructure" "$IN/raw/$R.exa-infrastructure.json" \
        '.data[] | "| \(.["display-name"]) | \(.shape // "-") | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | Shape | State | OCID |
|---|---|---|---|'

    section "VM clusters" "$IN/raw/$R.vm-clusters.json" \
        '.data[] | "| \(.["display-name"]) | \(.["cpu-core-count"] // "-") | \(.["node-count"] // "-") | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | OCPU | Nodes | State | OCID |
|---|---|---|---|---|'

    section "Database systems" "$IN/raw/$R.db-systems.json" \
        '.data[] | "| \(.["display-name"]) | \(.shape // "-") | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | Shape | State | OCID |
|---|---|---|---|'

    section "Compute instances" "$IN/raw/$R.instances.json" \
        '.data[] | "| \(.["display-name"]) | \(.shape) | \(.["availability-domain"]) | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | Shape | AD | State | OCID |
|---|---|---|---|---|'

    section "Volume groups" "$IN/raw/$R.volume-groups.json" \
        '.data[] | "| \(.["display-name"]) | \(.["availability-domain"]) | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | AD | State | OCID |
|---|---|---|---|'

    section "Load balancers" "$IN/raw/$R.load-balancers.json" \
        '.data[] | "| \(.["display-name"]) | \(.["shape-name"] // "-") | \(if .["is-private"] then "private" else "public" end) | `\(.id)` |"' \
        '| Name | Shape | Visibility | OCID |
|---|---|---|---|'

    section "DNS steering policies" "$IN/raw/$R.steering-policies.json" \
        '.data[] | "| \(.["display-name"]) | \(.template // "-") | `\(.id)` |"' \
        '| Name | Template | OCID |
|---|---|---|'

    section "Full Stack DR protection groups" "$IN/raw/$R.drpgs.json" \
        '.data[] | "| \(.["display-name"]) | \(.role // "-") | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | Role | State | OCID |
|---|---|---|---|'

    section "Recovery Service protected databases" "$IN/raw/$R.protected-databases.json" \
        '.data[] | "| \(.["display-name"]) | \(.["lifecycle-state"]) | `\(.id)` |"' \
        '| Name | State | OCID |
|---|---|---|'

    section "Object Storage buckets" "$IN/raw/$R.buckets.json" \
        '.data[] | "| \(.name) | \(.["storage-tier"] // "-") |"' \
        '| Bucket | Storage tier |
|---|---|'

    section "Monitoring alarms" "$IN/raw/$R.alarms.json" \
        '.data[] | "| \(.["display-name"]) | \(.severity // "-") | \(if .["is-enabled"] then "enabled" else "DISABLED" end) |"' \
        '| Alarm | Severity | State |
|---|---|---|'
done

{
    printf '\n---\n\n## What this inventory cannot tell you\n\n'
    printf '| Question | Answered by |\n|---|---|\n'
    printf '| What each resource is for | The application owner (`itscp-interview-application`) |\n'
    printf '| Whether replication is current | Monitoring lag metrics, not a resource listing |\n'
    printf '| What is missing that should exist | Someone who expected it (`itscp-interview-infrastructure`) |\n'
    printf '| Whether the environment matches its documentation | The infrastructure interview |\n'
} >> "$OUT"

printf 'wrote %s\n' "$OUT"
