#!/usr/bin/env bash
# emit-dr-resources-env.sh — populate the resource file the runbook scripts read.
# Pure rendering from raw discovery JSON; makes no API calls.
#
# Fields discovery cannot determine are emitted as REPLACE-<reason> so that a
# half-populated file is obvious rather than plausible.

set -uo pipefail
IN="discovery-output"; OUT="discovery-output/dr-resources.env"; REGIONS=""
while [ $# -gt 0 ]; do
    case "$1" in
        --in) IN="$2"; shift 2 ;;
        --out) OUT="$2"; shift 2 ;;
        --regions) REGIONS="$2"; shift 2 ;;
        *) shift ;;
    esac
done

HAVE_JQ=0; command -v jq >/dev/null 2>&1 && HAVE_JQ=1
j() { [ "$HAVE_JQ" -eq 1 ] && [ -f "$1" ] && jq -r "$2" "$1" 2>/dev/null | tr '\n' ' ' | sed 's/ $//' || true; }

IFS=',' read -r -a RL <<< "${REGIONS:-}"
PRIMARY="${RL[0]:-REPLACE-primary-region}"
DR="${RL[1]:-REPLACE-dr-region}"

{
    printf '# dr-resources.env — generated by itscm-onboarding discovery on %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    printf '#\n'
    printf '# GENERATED, NOT VERIFIED. Discovery reports what exists; it cannot tell which\n'
    printf '# resource plays which role in your recovery. Every value below must be confirmed\n'
    printf '# by the infrastructure owner before any runbook script consumes it.\n'
    printf '#\n'
    printf '# Values shown as REPLACE-<reason> could not be determined by a read-only walk.\n'
    printf '# This file contains your resource inventory. Keep it gitignored.\n\n'

    printf 'PRIMARY_REGION="%s"\n' "$PRIMARY"
    printf 'DR_REGION="%s"\n\n' "$DR"

    printf '# --- Compartments ---\n'
    printf 'PRIMARY_COMPARTMENT_OCID="%s"\n' "$(j "$IN/raw/$PRIMARY.compartments.json" '.data[0].id // empty')"
    printf 'DR_COMPARTMENT_OCID="%s"\n\n' "$(j "$IN/raw/$DR.compartments.json" '.data[0].id // empty')"

    printf '# --- Exadata / VM clusters ---\n'
    printf '# Which cluster is primary and which is standby is a role, not a property.\n'
    printf 'PRIMARY_VMCLUSTER_OCID="%s"\n' "$(j "$IN/raw/$PRIMARY.vm-clusters.json" '.data[0].id // empty')"
    printf 'DR_VMCLUSTER_OCID="%s"\n' "$(j "$IN/raw/$DR.vm-clusters.json" '.data[0].id // empty')"
    printf 'DR_EXA_INFRA_OCID="%s"\n' "$(j "$IN/raw/$DR.exa-infrastructure.json" '.data[0].id // empty')"
    printf 'PRIMARY_VMCLUSTER_NODE_COUNT="%s"\n' "$(j "$IN/raw/$PRIMARY.vm-clusters.json" '.data[0]["node-count"] // empty')"
    printf 'DR_VMCLUSTER_NODE_COUNT="%s"\n' "$(j "$IN/raw/$DR.vm-clusters.json" '.data[0]["node-count"] // empty')"
    printf 'DR_OCPU_FLOOR="REPLACE-ask-infrastructure-owner"\n'
    printf 'DR_OCPU_PRODUCTION="%s"\n\n' "$(j "$IN/raw/$PRIMARY.vm-clusters.json" '.data[0]["cpu-core-count"] // empty')"

    printf '# --- Data Guard ---\n'
    printf '# Connect strings hold credentials; discovery never reads or writes them.\n'
    printf 'DG_CONNECT="REPLACE-credentials-never-discovered"\n'
    printf 'DG_PRIMARY="REPLACE-ask-dba"\n'
    printf 'DG_STANDBY_REMOTE="REPLACE-ask-dba"\n\n'

    printf '# --- Compute ---\n'
    printf '# Every instance found in the DR region. Which are app tier, which are always-on,\n'
    printf '# and which are drill-only is a role the infrastructure owner assigns.\n'
    printf 'DR_APP_INSTANCE_OCIDS="%s"\n' "$(j "$IN/raw/$DR.instances.json" '.data[].id')"
    printf 'DR_ALWAYS_ON_INSTANCE_OCIDS="REPLACE-ask-infrastructure-owner"\n'
    printf 'DR_DRILL_INSTANCE_OCIDS="REPLACE-ask-infrastructure-owner"\n\n'

    printf '# --- Storage ---\n'
    printf 'PRIMARY_VOLUME_GROUP_OCIDS="%s"\n' "$(j "$IN/raw/$PRIMARY.volume-groups.json" '.data[].id')"
    printf 'DR_VOLUME_GROUP_REPLICA_OCIDS="%s"\n' "$(cat "$IN"/raw/"$DR".vg-replicas.*.json 2>/dev/null | { [ "$HAVE_JQ" -eq 1 ] && jq -r '.data[].id' 2>/dev/null || true; } | tr '\n' ' ' | sed 's/ $//')"
    printf 'DR_FSS_REPLICATION_OCIDS="%s"\n\n' "$(cat "$IN"/raw/"$DR".fs-replications.*.json 2>/dev/null | { [ "$HAVE_JQ" -eq 1 ] && jq -r '.data[].id' 2>/dev/null || true; } | tr '\n' ' ' | sed 's/ $//')"

    printf '# --- Load balancer and steering ---\n'
    printf 'PRIMARY_LB_OCID="%s"\n' "$(j "$IN/raw/$PRIMARY.load-balancers.json" '.data[0].id // empty')"
    printf 'DR_LB_OCID="%s"\n' "$(j "$IN/raw/$DR.load-balancers.json" '.data[0].id // empty')"
    printf 'DR_LB_BACKENDSET="REPLACE-ask-infrastructure-owner"\n'
    printf 'DR_STEERING_POLICY_OCID="%s"\n\n' "$(j "$IN/raw/$PRIMARY.steering-policies.json" '.data[0].id // empty')"

    printf '# --- Full Stack DR and Recovery Service ---\n'
    printf 'DR_FSDR_DRPG_OCIDS="%s %s"\n' "$(j "$IN/raw/$PRIMARY.drpgs.json" '.data[].id')" "$(j "$IN/raw/$DR.drpgs.json" '.data[].id')"
    printf 'DR_PROTECTED_DB_OCIDS="%s"\n' "$(j "$IN/raw/$PRIMARY.protected-databases.json" '.data[].id')"
} > "$OUT"

chmod 600 "$OUT" 2>/dev/null || true
printf 'wrote %s (mode 600)\n' "$OUT"
