"""The committed manual, rebuilt from its sources and compared byte for byte.

``docs/manual/`` is generated output that is committed on purpose, like ``examples/``, and it
rots the same way: a skill grows a section, the question bank grows a field, and the manual
quietly stops being what a person following it would need. This section is the guard.

It also holds the joins that make the manual complete rather than merely current. A namespace
claimed by no phase is a field nobody would ever be asked for; a namespace claimed by two is a
field asked twice by different people, which is how a store gets a contradiction that nobody
put there. Both are checked here rather than left to a reader noticing.
"""
from __future__ import annotations

import re
import sys
from dataclasses import fields as dataclass_fields
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import itscp_manual as manual
import itscp_questions as bank
import itscp_store as store
from harness import Section, equal

MANUAL_DIR = manual.OUTPUT_DIR

#: A relative link to another page of the manual, which has to resolve.
_LINK = re.compile(r"\]\((?P<target>[0-9A-Za-z][0-9A-Za-z._-]*\.md)\)")

#: The heading of one field's block, which is how a question is counted as asked.
_FIELD_HEADING = re.compile(r"^#### `(?P<key>[a-z0-9_.]+)`$", re.M)


def main() -> None:
    section = Section("11", "the committed manual")

    section.check("the manual directory exists", _manual_exists)
    section.check("every page is what the sources generate now", _pages_match)
    section.check("no page is generated by nothing", _no_orphan_pages)
    section.check("every page says it is generated", _every_page_carries_the_banner)
    section.check("every field is asked exactly once", _every_field_asked_once)
    section.check("no phase claims another phase's namespace", _namespaces_partition)
    section.check("every namespace has a phase", _namespaces_covered)
    section.check("the record table covers the record", _record_fields_described)
    section.check("every interview phase names its interviewee", _sessions_name_their_room)
    section.check("every link between pages resolves", _links_resolve)
    section.check("a renamed skill section fails the build", _extraction_is_strict)

    section.finish()


def _manual_exists() -> None:
    assert MANUAL_DIR.is_dir(), (
        f"{MANUAL_DIR} is missing; generate it with python3 plugin/itscp_manual.py")


def _pages_match() -> None:
    """Byte for byte, but reported as the first line that differs.

    A page is a few hundred lines and printing both copies of one buries the change that
    caused the failure in forty kilobytes of the text that did not change. What a reader
    needs is the line number and the two versions of that line, which is also the shape of
    the fix: regenerate, or reconsider the source edit.
    """
    for name, content in sorted(manual.pages().items()):
        path = MANUAL_DIR / name
        assert path.exists(), f"docs/manual/{name} is missing; regenerate the manual"
        committed = path.read_text(encoding="utf-8")
        if committed == content:
            continue
        raise AssertionError(
            f"docs/manual/{name} is not what its sources generate now. "
            "Regenerate with python3 plugin/itscp_manual.py.\n"
            + _first_difference(committed, content))


def _first_difference(committed: str, generated: str) -> str:
    """The first line the two copies disagree on, named and shown."""
    left = committed.splitlines()
    right = generated.splitlines()
    for number, (before, after) in enumerate(zip(left, right), start=1):
        if before != after:
            return (f"  line {number}\n"
                    f"    committed: {before!r}\n"
                    f"    generated: {after!r}")
    shorter, longer = ("committed", "generated") if len(left) < len(right) else ("generated",
                                                                                 "committed")
    return (f"  the two agree for {min(len(left), len(right))} lines; the {shorter} copy ends "
            f"there and the {longer} copy continues to line {max(len(left), len(right))}")


def _no_orphan_pages() -> None:
    generated = set(manual.pages())
    committed = {path.name for path in MANUAL_DIR.glob("*.md")}
    orphans = sorted(committed - generated)
    assert not orphans, (
        "docs/manual/ holds pages nothing generates: " + ", ".join(orphans)
        + ". Regenerate; the generator removes them.")


def _every_page_carries_the_banner() -> None:
    for name, content in sorted(manual.pages().items()):
        assert manual._BANNER in content, (
            f"docs/manual/{name} does not say it is generated, so a reader would edit it")


def _every_field_asked_once() -> None:
    """The manual asks for exactly the bank, no more and no fewer."""
    asked: dict[str, list[str]] = {}
    for name, content in manual.pages().items():
        if name in ("README.md", "method.md", "fields.md"):
            continue
        for match in _FIELD_HEADING.finditer(content):
            asked.setdefault(match.group("key"), []).append(name)
    twice = sorted(key for key, pages in asked.items() if len(pages) > 1)
    assert not twice, "asked on more than one page: " + ", ".join(twice)
    missing = sorted(set(bank.STARTER_KEYS) - set(asked))
    assert not missing, (
        "in the bank and asked by no phase of the manual: " + ", ".join(missing)
        + ". A namespace was added without a phase to record it.")
    invented = sorted(set(asked) - set(bank.STARTER_KEYS))
    assert not invented, "asked by the manual and not in the bank: " + ", ".join(invented)


def _namespaces_partition() -> None:
    claimed: dict[str, list[str]] = {}
    for phase in manual.PHASES:
        for namespace in phase.namespaces:
            claimed.setdefault(namespace, []).append(phase.slug)
    shared = sorted(name for name, phases in claimed.items() if len(phases) > 1)
    assert not shared, (
        "claimed by more than one phase: " + ", ".join(shared)
        + ". Two interviews recording one namespace is how a store gets a contradiction "
          "nobody argued about.")


def _namespaces_covered() -> None:
    claimed = {namespace for phase in manual.PHASES for namespace in phase.namespaces}
    equal(sorted(claimed), sorted(bank.NAMESPACES), "the namespaces the manual's phases cover")


def _record_fields_described() -> None:
    described = set(manual.RECORD_FIELD_NOTES)
    actual = {field.name for field in dataclass_fields(store.Record)}
    equal(sorted(described), sorted(actual),
          "the record fields the manual describes against the record itself")


def _sessions_name_their_room() -> None:
    for phase in manual.PHASES:
        if not phase.session:
            continue
        _, body, path = manual._skill(phase.skills[0])
        for label in ("Interviewee", "Time"):
            value = manual._bold_field(body, label, path)
            assert value, f"{path} has an empty **{label}:** line"


def _links_resolve() -> None:
    pages = manual.pages()
    for name, content in sorted(pages.items()):
        for match in _LINK.finditer(content):
            target = match.group("target")
            assert target in pages, (
                f"docs/manual/{name} links to {target}, which the manual does not generate")


def _extraction_is_strict() -> None:
    """The tripwire that makes this whole file work: extraction refuses, never guesses."""
    for attempt, expected in (
        (lambda: manual._section("## Something else\n\nbody\n", "Before you start",
                                 Path("nowhere.md")), "no '## Before you start' section"),
        (lambda: manual._bold_field("no marker here\n", "Interviewee", Path("nowhere.md")),
         "no longer carries a **Interviewee:** line"),
        (lambda: manual._frontmatter("# not a skill\n", Path("nowhere.md")),
         "has no frontmatter block"),
    ):
        try:
            attempt()
        except manual.ManualError as refusal:
            assert expected in str(refusal), (
                f"refused, but for the wrong reason: {refusal}")
            continue
        raise AssertionError(f"extraction accepted a source missing its {expected!r}")


if __name__ == "__main__":
    main()
