"""The committed manual, rebuilt from its sources and compared byte for byte.

``docs/manual/`` is generated output that is committed on purpose, like ``examples/``, and it
rots the same way: a skill grows a section, the question bank grows a field, and the manual
quietly stops being what a room following it would need. This section is the guard.

Three of the checks here are about a failure the byte comparison cannot see, because the
manual would still match its own generator while being wrong for its reader:

* **A skill section nobody classified.** Sections are carried by name, so a section added to a
  skill is silently absent from the manual. Every ``##`` heading of every embedded skill has
  to be either carried by a page or listed in ``SKIPPED_SECTIONS`` with a reason.
* **A tool reference nothing translates.** The manual is run by people with nothing installed.
  Any command-shaped text that survives into a page has to be answered by that page's
  *Running this without the toolkit* table, or the page is telling a room to run something it
  does not have.
* **A by-hand check for a finding the code no longer makes.** The register is checked on a
  wall against five named findings. If the validator stops raising one, the manual is
  teaching a room to look for something nobody considers a problem.
"""
from __future__ import annotations

import re
import sys
from dataclasses import fields as dataclass_fields
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent))

import itscp_manual as manual
import itscp_questions as bank
import itscp_store as store
from harness import Section, equal

MANUAL_DIR = manual.OUTPUT_DIR

#: A relative link to another page of the manual, which has to resolve.
_LINK = re.compile(r"\]\((?P<target>[0-9A-Za-z][0-9A-Za-z._-]*\.(?:md|html))(?:#[-\w]+)?\)")

#: The heading of one field's block, which is how a question is counted as asked.
_FIELD_HEADING = re.compile(r"^#### `(?P<key>[a-z0-9_.]+)`$", re.M)

#: Command-shaped text: something to run, or a file only the toolkit writes. Deliberately
#: written independently of :data:`itscp_manual.TRANSLATIONS` — a scan built from the same
#: list it is checking would agree with itself and catch nothing.
_TOOL_SHAPED = re.compile(
    r"\b(?:python3|bash|sh)[ \t]+\S+"
    r"|\b[\w/-]+\.(?:py|sh|toml|yaml)\b"
    r"|\bpicoagent\b"
    r"|\bitscp[-_][a-z_]+\b")

#: The generated-file comment at the top of every page, which never renders and is the one
#: place a command belongs: it is addressed to whoever regenerates the manual.
_COMMENT = re.compile(r"<!--.*?-->", re.S)


def main() -> None:
    section = Section("11", "the committed manual")

    section.check("the manual directory exists", _manual_exists)
    section.check("every page is what the sources generate now", _pages_match)
    section.check("no page is generated by nothing", _no_orphan_pages)
    section.check("every page says it is generated", _every_page_carries_the_banner)
    section.check("every skill section is carried or skipped by name", _sections_classified)
    section.check("no page tells the room to run anything", _no_tool_instructions)
    section.check("every replaced passage is still in its source", _substitutions_still_apply)
    section.check("every embedded skill renames to a phase", _renames_cover_the_embeds)
    section.check("the by-hand checks match the findings the code makes", _findings_exist)
    section.check("every field is asked exactly once", _every_field_asked_once)
    section.check("every field with a phase has a worksheet line", _worksheets_cover_the_fields)
    section.check("no phase claims another phase's namespace", _namespaces_partition)
    section.check("every namespace has a phase", _namespaces_covered)
    section.check("the transcription table covers the record", _record_fields_described)
    section.check("every session names whose answers they are", _sessions_name_their_room)
    section.check("every link between pages resolves", _links_resolve)
    section.check("a renamed skill section fails the build", _extraction_is_strict)

    section.finish()


def _manual_exists() -> None:
    assert MANUAL_DIR.is_dir(), (
        f"{MANUAL_DIR} is missing; generate it with python3 plugin/itscp_manual.py")


def _pages_match() -> None:
    """Byte for byte, but reported as the first line that differs.

    A page is a few hundred lines and printing both copies of one buries the change that
    caused the failure in forty kilobytes of the text that did not change. What a reader
    needs is the line number and the two versions of that line, which is also the shape of
    the fix: regenerate, or reconsider the source edit.
    """
    for name, content in sorted(manual.pages().items()):
        path = MANUAL_DIR / name
        assert path.exists(), f"docs/manual/{name} is missing; regenerate the manual"
        committed = path.read_text(encoding="utf-8")
        if committed == content:
            continue
        raise AssertionError(
            f"docs/manual/{name} is not what its sources generate now. "
            "Regenerate with python3 plugin/itscp_manual.py.\n"
            + _first_difference(committed, content))


def _first_difference(committed: str, generated: str) -> str:
    """The first line the two copies disagree on, named and shown."""
    left = committed.splitlines()
    right = generated.splitlines()
    for number, (before, after) in enumerate(zip(left, right), start=1):
        if before != after:
            return (f"  line {number}\n"
                    f"    committed: {before!r}\n"
                    f"    generated: {after!r}")
    shorter, longer = ("committed", "generated") if len(left) < len(right) else ("generated",
                                                                                 "committed")
    return (f"  the two agree for {min(len(left), len(right))} lines; the {shorter} copy ends "
            f"there and the {longer} copy continues to line {max(len(left), len(right))}")


def _no_orphan_pages() -> None:
    generated = set(manual.pages())
    committed = {path.name for path in MANUAL_DIR.glob("*.md")}
    orphans = sorted(committed - generated)
    assert not orphans, (
        "docs/manual/ holds pages nothing generates: " + ", ".join(orphans)
        + ". Regenerate; the generator removes them.")


def _every_page_carries_the_banner() -> None:
    for name, content in sorted(manual.pages().items()):
        assert manual._BANNER in content, (
            f"docs/manual/{name} does not say it is generated, so a reader would edit it")


def _embeds() -> dict[str, set[str]]:
    """Every skill the manual embeds, and the section headings it carries from each."""
    carried: dict[str, set[str]] = {}
    groups = [phase.embeds for phase in manual.PHASES]
    groups += [manual.METHOD_EMBEDS, manual.COVERAGE_EMBEDS, manual.STORE_EMBEDS]
    for group in groups:
        for embed in group:
            carried.setdefault(embed.skill, set()).update(embed.sections)
    return carried


def _sections_classified() -> None:
    for skill, carried in sorted(_embeds().items()):
        available = set(manual.skill_sections(skill))
        skipped = {heading for heading, _ in manual.SKIPPED_SECTIONS.get(skill, ())}
        unclassified = sorted(available - carried - skipped)
        assert not unclassified, (
            f"{skill} has sections the manual neither carries nor skips: "
            + ", ".join(unclassified)
            + ". Add each to the page that should carry it, or to SKIPPED_SECTIONS with the "
              "reason it is left out.")
        gone = sorted((carried | skipped) - available)
        assert not gone, (
            f"{skill} no longer has these sections: " + ", ".join(gone)
            + ". They were renamed or removed; update the page or SKIPPED_SECTIONS.")


def _no_tool_instructions() -> None:
    """Nothing a room cannot do.

    The manual is run by people with nothing installed, so a command, a script or a module
    name in a page is not a small blemish: it is the page telling a facilitator it was written
    for somebody else. The scan pattern is written independently of ``SUBSTITUTIONS`` on
    purpose. One built from the same list it is checking would agree with itself and catch
    nothing.

    The HTML comment at the top of each page is exempt, and is where the regeneration command
    lives. It is addressed to whoever maintains the repository and never renders.
    """
    for name, content in sorted(manual.pages().items()):
        visible = _COMMENT.sub("", content)
        hits = sorted({match.group(0) for match in _TOOL_SHAPED.finditer(visible)})
        assert not hits, (
            f"docs/manual/{name} names " + ", ".join(repr(hit) for hit in hits)
            + ". A room has none of that. Add a SUBSTITUTIONS entry saying what they do "
              "instead, or skip the section that says it.")


def _substitutions_still_apply() -> None:
    """A replacement is only safe while the passage it stands in for is still there.

    Rendering already raises when one goes missing, so this check exists to say which one and
    to fail with the reason rather than with a stack trace.
    """
    for (source, heading), entries in sorted(manual.SUBSTITUTIONS.items()):
        if source.endswith(".md"):
            text = manual._section(manual._read(manual.ROOT / source), heading,
                                   manual.ROOT / source)
        elif heading:
            sections = manual.skill_sections(source)
            assert heading in sections, f"{source} has no '## {heading}' section any more"
            text = sections[heading]
        else:
            text = manual.skill_preamble(source)
        for original, _, reason in entries:
            assert original in text, (
                f"{source} '{heading}' no longer contains the passage the manual replaces "
                f"({reason}). Re-read the section and update SUBSTITUTIONS.")


def _renames_cover_the_embeds() -> None:
    """Every interview skill a page carries has a phase to be renamed to."""
    renamed = manual._renames()
    for phase in manual.PHASES:
        for embed in phase.embeds:
            if embed.skill.startswith("_method/"):
                continue
            assert renamed.get(embed.skill) == f"phase {phase.number}", (
                f"{embed.skill} is carried by phase {phase.number} and renames to "
                f"{renamed.get(embed.skill)!r}")


def _findings_exist() -> None:
    """The wall checks name findings; the validator has to still make them."""
    source = (manual.PLUGIN / "itscp_portfolio.py").read_text(encoding="utf-8")
    for finding in manual.REGISTER_FINDINGS:
        assert f'"{finding}"' in source, (
            f"the manual teaches a by-hand check for {finding!r} and itscp_portfolio no "
            "longer raises it. The room would be looking for something that is not a "
            "problem any more.")
    page = (MANUAL_DIR / "00-portfolio.md").read_text(encoding="utf-8")
    for finding in manual.REGISTER_FINDINGS:
        assert finding in page, f"{finding!r} is named in REGISTER_FINDINGS and not on the page"


def _every_field_asked_once() -> None:
    """The manual asks for exactly the bank, no more and no fewer."""
    asked: dict[str, list[str]] = {}
    for name, content in manual.pages().items():
        if name in ("README.md", "method.md", "fields.md"):
            continue
        for match in _FIELD_HEADING.finditer(content):
            asked.setdefault(match.group("key"), []).append(name)
    twice = sorted(key for key, pages in asked.items() if len(pages) > 1)
    assert not twice, "asked on more than one page: " + ", ".join(twice)
    missing = sorted(set(bank.STARTER_KEYS) - set(asked))
    assert not missing, (
        "in the bank and asked by no phase of the manual: " + ", ".join(missing)
        + ". A namespace was added without a phase to record it.")
    invented = sorted(set(asked) - set(bank.STARTER_KEYS))
    assert not invented, "asked by the manual and not in the bank: " + ", ".join(invented)


def _worksheets_cover_the_fields() -> None:
    """Every answer a phase must come away with has a line to write it on."""
    for phase in manual.PHASES:
        questions = manual._questions_for(phase.namespaces)
        if not questions:
            continue
        page = manual.pages()[f"{phase.slug}.md"]
        worksheet = page.split("## The worksheet", 1)
        assert len(worksheet) == 2, (
            f"phase {phase.number} records {len(questions)} answers and has no worksheet")
        for question in questions:
            assert f"`{question.id}`" in worksheet[1], (
                f"phase {phase.number}'s worksheet has no line for {question.id}")


def _namespaces_partition() -> None:
    claimed: dict[str, list[str]] = {}
    for phase in manual.PHASES:
        for namespace in phase.namespaces:
            claimed.setdefault(namespace, []).append(phase.slug)
    shared = sorted(name for name, phases in claimed.items() if len(phases) > 1)
    assert not shared, (
        "claimed by more than one phase: " + ", ".join(shared)
        + ". Two sessions recording one namespace is how a store gets a contradiction "
          "nobody argued about.")


def _namespaces_covered() -> None:
    claimed = {namespace for phase in manual.PHASES for namespace in phase.namespaces}
    equal(sorted(claimed), sorted(bank.NAMESPACES), "the namespaces the manual's phases cover")


def _record_fields_described() -> None:
    described = set(manual.RECORD_FIELD_NOTES)
    actual = {field.name for field in dataclass_fields(store.Record)}
    equal(sorted(described), sorted(actual),
          "the record fields the transcription appendix describes against the record itself")


def _sessions_name_their_room() -> None:
    for phase in manual.PHASES:
        if not phase.session:
            continue
        _, body, path = manual._skill_body(phase.embeds[0].skill)
        for label in ("Interviewee", "Time"):
            value = manual._bold_field(body, label, path)
            assert value, f"{path} has an empty **{label}:** line"


def _links_resolve() -> None:
    pages = manual.files()
    for name, content in sorted(pages.items()):
        for match in _LINK.finditer(content):
            target = match.group("target")
            assert target in pages, (
                f"docs/manual/{name} links to {target}, which the manual does not generate")


def _extraction_is_strict() -> None:
    """The tripwire that makes this whole file work: extraction refuses, never guesses."""
    for attempt, expected in (
        (lambda: manual._section("## Something else\n\nbody\n", "Before you start",
                                 Path("nowhere.md")), "no '## Before you start' section"),
        (lambda: manual._bold_field("no marker here\n", "Interviewee", Path("nowhere.md")),
         "no longer carries a **Interviewee:** line"),
        (lambda: manual._frontmatter("# not a skill\n", Path("nowhere.md")),
         "has no frontmatter block"),
        (lambda: manual._embedded((manual.Embed("itscp-audit", ("Not a heading",)),)),
         "has no '## Not a heading' section"),
    ):
        try:
            attempt()
        except manual.ManualError as refusal:
            assert expected in str(refusal), (
                f"refused, but for the wrong reason: {refusal}")
            continue
        raise AssertionError(f"extraction accepted a source missing its {expected!r}")


if __name__ == "__main__":
    main()
