"""The per-session interview transcript: what was asked, what was said, and in what order.

Distinct from the answer store and never a substitute for it. The store holds current state;
a superseded value is no longer current, so the store cannot answer "where did the four-hour
figure come from, and who said it". The transcript can, because it is append only in the
same sense :func:`itscp_store.supersede` is: entries are added, never rewritten.

Three things this records that the store cannot:

**Questions that got no answer.** An unanswered question with a named owner is the toolkit's
most valuable single output. In the store that is one MISSING record; here it is the event,
the words the interviewee actually used, and who was named as the person who would know.

**Read-backs.** Where prose is drafted from someone's understanding and then shown back to
them, the confirmation is what makes it an answer they gave rather than one we invented. The
draft, what was shown, and whether they confirmed, corrected or rejected it are three
separate events. The store carries the outcome on the record; the transcript carries the
cycle, which is what an auditor asks for.

**Order.** Two answers given fifteen minutes apart, the second correcting the first, are two
events here and one value in the store.

Same sensitivity as the answer store, and more of it: the store names roles, the transcript
names people. It is gitignored on the same terms and the emitted file says so at the top.
"""
from __future__ import annotations

import sys

if sys.version_info < (3, 11):
    raise RuntimeError(
        "itscp-author needs Python 3.11 or newer (this is "
        f"{sys.version_info.major}.{sys.version_info.minor}). The transcript reads TOML "
        "through the standard library's tomllib, added in 3.11. There is no pip dependency "
        "to install; run the plugin under a newer interpreter."
    )

import os
import tomllib
from dataclasses import dataclass
from pathlib import Path

import itscp_questions as bank
from itscp_store import StoreError, ValidationError, toml_value

SCHEMA_VERSION = 1

#: The closed set of things that can happen to one question in one session.
#:
#: ``asked``
#:     The question was put, in the words recorded in ``prompt``.
#: ``answered``
#:     The interviewee answered. ``answer`` is their words, not a summary of them.
#: ``unanswered``
#:     The question was put and produced no answer. Records who would know, which is why
#:     this is an event and not an absence.
#: ``deferred``
#:     Postponed deliberately, with a date.
#: ``not_applicable``
#:     Ruled out, with a reason.
#: ``drafted``
#:     Prose was drafted from what the interviewee described plus any sources read. A draft
#:     is not an answer and never reaches the store on its own.
#: ``readback_confirmed`` / ``readback_corrected`` / ``readback_rejected``
#:     The draft was shown back. Confirmed means accepted as written; corrected means the
#:     interviewee changed it and the change is theirs; rejected means it was wrong and the
#:     field goes back to unanswered.
#: ``conflict_raised``
#:     A second source disagreed with a recorded value.
#: ``superseded``
#:     A recorded value was replaced, with the reason given in the room.
EVENTS: tuple[str, ...] = (
    "asked", "answered", "unanswered", "deferred", "not_applicable", "drafted",
    "readback_confirmed", "readback_corrected", "readback_rejected", "conflict_raised",
    "superseded",
)

#: Events that only make sense once something has been drafted and shown back.
_READBACK_EVENTS = ("readback_confirmed", "readback_corrected", "readback_rejected")

#: Events that must carry the interviewee's own words.
_EVENTS_NEEDING_AN_ANSWER = ("answered", "unanswered") + _READBACK_EVENTS

_SENSITIVITY_NOTICE = (
    "The interview transcript. Append only: entries are added, never rewritten.",
    "",
    "THIS FILE IS GITIGNORED AND MUST STAY THAT WAY, on the same terms as the answer",
    "store and then some. The store names roles; this file names people, quotes them,",
    "and records what their organisation does not know. Treat it as the most sensitive",
    "artefact of the engagement.",
    "",
    "Generated by itscp_session.emit. A correction is a new entry, not an edit to an old",
    "one, so the order below is the order the conversation happened in.",
)


@dataclass(frozen=True)
class Entry:
    """One thing that happened to one question, at one moment, with one person.

    ``prompt`` is the question exactly as asked and ``answer`` the reply exactly as given.
    Neither is a summary: a summary is the interviewer's words, and the whole point of the
    transcript is that it holds the interviewee's.

    ``mutation`` names what the answer did to the store, as free text such as
    ``business.mtd.tier0 ANSWERED confidence=medium``. An event that changed nothing leaves
    it empty, which is itself worth being able to see.
    """

    event: str
    at: str
    interviewee_role: str
    interviewee_name: str
    question_id: str
    prompt: str
    answer: str = ""
    drafted: str = ""
    owner: str = ""
    due: str = ""
    mutation: str = ""
    notes: str = ""


def validate(entry: Entry) -> None:
    """Raise :class:`ValidationError` naming the first rule ``entry`` breaks."""
    if entry.event not in EVENTS:
        raise ValidationError(
            f"event must be one of {', '.join(EVENTS)}; got {entry.event!r}")
    if bank.question(entry.question_id) is None:
        raise ValidationError(
            f"{entry.question_id!r} is not a key in the question bank, so this entry records "
            f"a conversation about a field that does not exist.")
    if not entry.at:
        raise ValidationError(
            f"{entry.question_id}: every entry is timestamped. An ordered record with no "
            f"times cannot answer when a figure changed.")
    if not entry.interviewee_role:
        raise ValidationError(
            f"{entry.question_id}: every entry names who was in the room, by role.")
    if entry.interviewee_role not in bank.OWNER_VOCABULARY:
        raise ValidationError(
            f"{entry.question_id}: interviewee_role must be a role from the roster; "
            f"got {entry.interviewee_role!r}")
    if not entry.prompt:
        raise ValidationError(
            f"{entry.question_id}: every entry records the prompt exactly as asked, so the "
            f"answer can be read against the question that produced it.")
    if entry.event in _EVENTS_NEEDING_AN_ANSWER and not entry.answer:
        raise ValidationError(
            f"{entry.question_id}: a {entry.event} entry records the answer exactly as "
            f"given. 'I do not know' is an answer and belongs here verbatim.")
    if entry.event == "unanswered" and not entry.owner:
        raise ValidationError(
            f"{entry.question_id}: an unanswered question records who would know. Without a "
            f"name it is a gap nobody closes, which is the one thing this event exists for.")
    if entry.event in _READBACK_EVENTS and not entry.drafted:
        raise ValidationError(
            f"{entry.question_id}: a read-back records what was shown to the interviewee. "
            f"Confirmation of nothing in particular is not attribution.")
    if entry.event == "drafted" and not entry.drafted:
        raise ValidationError(
            f"{entry.question_id}: a drafted entry records the draft.")


def new_transcript(session_id: str, system_name: str) -> dict:
    """An empty transcript for one session."""
    return {
        "meta": {
            "schema_version": SCHEMA_VERSION,
            "session_id": session_id,
            "system_name": system_name,
        },
        "entries": (),
    }


def append(transcript: dict, entry: Entry) -> dict:
    """A copy of ``transcript`` with ``entry`` on the end, after validating it.

    Returns a new transcript rather than mutating one, so a rejected entry cannot leave a
    half-written record and an earlier transcript object stays exactly as it was. That is
    what append only means here: no operation in this module can change an entry already in
    a transcript.
    """
    validate(entry)
    return {**transcript, "entries": tuple(transcript["entries"]) + (entry,)}


def for_question(transcript: dict, question_id: str) -> list[Entry]:
    """Every entry about one question, in the order it happened.

    This is the answer to "where did the four-hour figure come from": the question as asked,
    the words that produced the figure, any draft shown back, and what was confirmed.
    """
    return [entry for entry in transcript["entries"] if entry.question_id == question_id]


def unanswered(transcript: dict) -> list[Entry]:
    """Every question asked in this session that produced no answer, with its named owner."""
    return [entry for entry in transcript["entries"] if entry.event == "unanswered"]


def emit(transcript: dict) -> str:
    """The whole transcript as TOML. Deterministic, so a diff shows only new entries."""
    lines = ["\n".join(f"# {line}" for line in _SENSITIVITY_NOTICE), "", "[meta]"]
    lines.extend(f"{name} = {toml_value(value)}"
                 for name, value in transcript["meta"].items())
    for entry in transcript["entries"]:
        lines.append("")
        lines.append("[[entries]]")
        lines.extend(f"{name} = {toml_value(value)}"
                     for name, value in vars(entry).items() if value != "")
    return "\n".join(lines) + "\n"


def load_transcript(parsed: dict) -> dict:
    """Turn a parsed TOML mapping back into entries. The inverse of :func:`emit`."""
    return {
        "meta": dict(parsed.get("meta", {})),
        "entries": tuple(_load_entry(table) for table in parsed.get("entries", ())),
    }


def _load_entry(table: dict) -> Entry:
    return Entry(**{name: table.get(name, "") for name in Entry.__dataclass_fields__})


def as_comparable(transcript: dict) -> dict:
    """``transcript`` reduced to plain data, for comparing a round trip to its original."""
    return {
        "meta": dict(transcript["meta"]),
        "entries": [{name: value for name, value in vars(entry).items() if value != ""}
                    for entry in transcript["entries"]],
    }


class SessionLog:
    """The transcript as a file: read it, append to it, never rewrite an entry."""

    def __init__(self, path: Path):
        self.path = path

    def read(self) -> dict:
        """The stored transcript, or an empty one. A corrupt file is reported, never reset."""
        if not self.path.exists():
            return new_transcript("", "")
        try:
            parsed = tomllib.loads(self.path.read_text(encoding="utf-8"))
        except (OSError, tomllib.TOMLDecodeError) as failure:
            raise StoreError(
                f"{self.path} is not readable as TOML ({failure}). Fix or move it; nothing "
                f"has been overwritten and no part of the interview has been lost."
            ) from failure
        return load_transcript(parsed)

    def write(self, transcript: dict) -> None:
        """Replace the file atomically. Interviews end unexpectedly; a partial file loses work."""
        self.path.parent.mkdir(parents=True, exist_ok=True)
        temporary = self.path.with_name(self.path.name + ".tmp")
        temporary.write_text(emit(transcript), encoding="utf-8")
        os.replace(temporary, self.path)

    def record(self, entry: Entry) -> dict:
        """Append one entry and write the file, in that order. Returns the new transcript.

        Writing after every entry rather than at the end of the session is the same rule the
        answer store follows and for the same reason: the conversation stops when the person
        leaves, not when the interviewer is finished.
        """
        transcript = append(self.read(), entry)
        self.write(transcript)
        return transcript
